[2025-06-27 14:06:40,514: INFO: main: Welcome to our custm logging Datascience]
[2025-06-27 19:56:43,768: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-27 19:56:43,780: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-27 19:56:43,781: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-27 19:56:43,783: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\src\datascience\utils\common.py", line 31, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "box\\box.py", line 295, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\main.py", line 9, in <module>
    data_ingestion.initiate_data_ingestion()
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\src\datascience\pipeline\data_ingestion.py", line 13, in initiate_data_ingestion
    config=ConfigurationManager()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\src\datascience\config\configuration.py", line 12, in __init__
    self.params=read_yaml(params_filepath)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\src\datascience\utils\common.py", line 33, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2025-06-27 19:58:09,980: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-27 19:58:09,983: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-27 19:58:09,990: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-27 19:58:09,992: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-27 19:58:09,994: INFO: common: created directory at: artifacts]
[2025-06-27 19:58:09,995: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-27 19:58:12,742: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 10EE:2F9F3:6FD8A4:7CD206:685EE9C3
Accept-Ranges: bytes
Date: Fri, 27 Jun 2025 18:58:12 GMT
Via: 1.1 varnish
X-Served-By: cache-par-lfpg1960096-PAR
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1751050692.015244,VS0,VE157
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 188f0198adb8c9fb4f6fd2db82b184caa7383a76
Expires: Fri, 27 Jun 2025 19:03:12 GMT
Source-Age: 0

]
[2025-06-27 19:58:12,778: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-27 22:14:56,609: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-27 22:14:56,645: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-27 22:14:56,651: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-27 22:14:56,659: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-27 22:14:56,664: INFO: common: created directory at: artifacts]
[2025-06-27 22:14:56,665: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-27 22:14:56,666: INFO: data_ingestion: File already exists]
[2025-06-27 22:14:56,682: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-27 22:14:56,684: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-06-27 22:14:56,689: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-27 22:14:56,699: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-27 22:14:56,710: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-27 22:14:56,715: INFO: common: created directory at: artifacts]
[2025-06-27 22:14:56,718: INFO: common: created directory at: artifacts/data_validation]
[2025-06-27 22:14:56,808: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-06-28 00:57:48,753: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-28 00:57:48,806: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 00:57:48,815: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 00:57:48,823: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 00:57:48,825: INFO: common: created directory at: artifacts]
[2025-06-28 00:57:48,827: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-28 00:57:48,830: INFO: data_ingestion: File already exists]
[2025-06-28 00:57:48,849: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-28 00:57:48,852: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-06-28 00:57:48,863: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 00:57:48,866: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 00:57:48,874: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 00:57:48,881: INFO: common: created directory at: artifacts]
[2025-06-28 00:57:48,883: INFO: common: created directory at: artifacts/data_validation]
[2025-06-28 00:57:49,011: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-06-28 00:57:49,013: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-06-28 00:57:49,046: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 00:57:49,049: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 00:57:49,054: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 00:57:49,055: INFO: common: created directory at: artifacts]
[2025-06-28 00:57:49,057: INFO: common: created directory at: artifacts/data_transformation]
[2025-06-28 00:57:49,132: INFO: data_transformation: Splited data into training and test sets]
[2025-06-28 00:57:49,133: INFO: data_transformation: (1199, 12)]
[2025-06-28 00:57:49,133: INFO: data_transformation: (400, 12)]
[2025-06-28 00:57:49,135: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-06-28 15:58:28,784: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-28 15:58:28,856: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 15:58:28,866: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 15:58:28,873: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 15:58:28,877: INFO: common: created directory at: artifacts]
[2025-06-28 15:58:28,880: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-28 15:58:28,881: INFO: data_ingestion: File already exists]
[2025-06-28 15:58:28,898: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-28 15:58:28,900: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-06-28 15:58:28,915: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 15:58:28,921: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 15:58:28,933: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 15:58:28,935: INFO: common: created directory at: artifacts]
[2025-06-28 15:58:28,937: INFO: common: created directory at: artifacts/data_validation]
[2025-06-28 15:58:29,021: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-06-28 15:58:29,022: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-06-28 15:58:29,031: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 15:58:29,036: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 15:58:29,045: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 15:58:29,046: INFO: common: created directory at: artifacts]
[2025-06-28 15:58:29,048: INFO: common: created directory at: artifacts/data_transformation]
[2025-06-28 15:58:29,153: INFO: data_transformation: Splited data into training and test sets]
[2025-06-28 15:58:29,154: INFO: data_transformation: (1199, 12)]
[2025-06-28 15:58:29,156: INFO: data_transformation: (400, 12)]
[2025-06-28 15:58:29,159: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-06-28 15:58:29,162: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-06-28 15:58:29,171: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 15:58:29,185: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 15:58:29,198: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 15:58:29,201: INFO: common: created directory at: artifacts]
[2025-06-28 15:58:29,214: INFO: common: created directory at: artifacts/model_trainer]
[2025-06-28 15:58:29,341: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-06-28 22:07:54,772: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-28 22:07:54,788: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 22:07:54,795: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 22:07:54,800: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 22:07:54,802: INFO: common: created directory at: artifacts]
[2025-06-28 22:07:54,802: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-28 22:07:54,804: INFO: data_ingestion: File already exists]
[2025-06-28 22:07:54,839: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-28 22:07:54,841: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-06-28 22:07:54,847: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 22:07:54,848: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 22:07:54,851: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 22:07:54,851: INFO: common: created directory at: artifacts]
[2025-06-28 22:07:54,852: INFO: common: created directory at: artifacts/data_validation]
[2025-06-28 22:07:54,893: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-06-28 22:07:54,894: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-06-28 22:07:54,912: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 22:07:54,913: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 22:07:54,915: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 22:07:54,919: INFO: common: created directory at: artifacts]
[2025-06-28 22:07:54,920: INFO: common: created directory at: artifacts/data_transformation]
[2025-06-28 22:07:54,964: INFO: data_transformation: Splited data into training and test sets]
[2025-06-28 22:07:54,965: INFO: data_transformation: (1199, 12)]
[2025-06-28 22:07:54,966: INFO: data_transformation: (400, 12)]
[2025-06-28 22:07:54,968: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-06-28 22:07:54,968: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-06-28 22:07:54,971: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 22:07:54,973: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 22:07:54,977: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 22:07:54,978: INFO: common: created directory at: artifacts]
[2025-06-28 22:07:54,979: INFO: common: created directory at: artifacts/model_trainer]
[2025-06-28 22:07:55,041: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-06-28 22:07:55,041: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-06-28 22:07:55,041: ERROR: main: name 'ModelEvaluationTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\main.py", line 55, in <module>
    data_ingestion = ModelEvaluationTrainingPipeline()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'ModelEvaluationTrainingPipeline' is not defined
[2025-06-28 22:09:05,995: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-28 22:09:05,999: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 22:09:06,000: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 22:09:06,002: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 22:09:06,003: INFO: common: created directory at: artifacts]
[2025-06-28 22:09:06,003: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-28 22:09:06,004: INFO: data_ingestion: File already exists]
[2025-06-28 22:09:06,007: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-28 22:09:06,007: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-06-28 22:09:06,011: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 22:09:06,015: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 22:09:06,017: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 22:09:06,018: INFO: common: created directory at: artifacts]
[2025-06-28 22:09:06,020: INFO: common: created directory at: artifacts/data_validation]
[2025-06-28 22:09:06,051: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-06-28 22:09:06,051: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-06-28 22:09:06,057: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 22:09:06,059: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 22:09:06,062: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 22:09:06,063: INFO: common: created directory at: artifacts]
[2025-06-28 22:09:06,064: INFO: common: created directory at: artifacts/data_transformation]
[2025-06-28 22:09:06,091: INFO: data_transformation: Splited data into training and test sets]
[2025-06-28 22:09:06,092: INFO: data_transformation: (1199, 12)]
[2025-06-28 22:09:06,092: INFO: data_transformation: (400, 12)]
[2025-06-28 22:09:06,093: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-06-28 22:09:06,094: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-06-28 22:09:06,099: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 22:09:06,100: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 22:09:06,102: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 22:09:06,103: INFO: common: created directory at: artifacts]
[2025-06-28 22:09:06,103: INFO: common: created directory at: artifacts/model_trainer]
[2025-06-28 22:09:06,175: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-06-28 22:09:06,175: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-06-28 22:09:06,178: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 22:09:06,178: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 22:09:06,180: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-28 22:09:06,181: INFO: common: created directory at: artifacts]
[2025-06-28 22:09:06,181: INFO: common: created directory at: artifacts/model_evaluation]
[2025-06-28 22:09:09,122: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2025-06-28 22:09:14,717: ERROR: main: INTERNAL_ERROR: Response: {'error': 'unsupported endpoint, please contact support@dagshub.com'}]
Traceback (most recent call last):
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\main.py", line 57, in <module>
    data_ingestion.initiate_model_evaluation()
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\src\datascience\pipeline\model_evaluation.py", line 15, in initiate_model_evaluation
    model_evaluation.log_into_mlflow()
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\src\datascience\components\model_evaluation.py", line 66, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model", registered_model_name="ElasticnetModel")
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\sklearn\__init__.py", line 426, in log_model
    return Model.log(
           ^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\models\model.py", line 1161, in log
    model = mlflow.initialize_logged_model(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\tracking\fluent.py", line 2130, in initialize_logged_model
    model = _create_logged_model(
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\tracking\fluent.py", line 2257, in _create_logged_model
    return MlflowClient().create_logged_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\tracking\client.py", line 5371, in create_logged_model
    return self._tracking_client.create_logged_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 824, in create_logged_model
    return self.store.create_logged_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 936, in create_logged_model
    response_proto = self._call_endpoint(CreateLoggedModel, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 135, in _call_endpoint
    return call_endpoint(
           ^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\utils\rest_utils.py", line 590, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\utils\rest_utils.py", line 304, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INTERNAL_ERROR: Response: {'error': 'unsupported endpoint, please contact support@dagshub.com'}
[2025-06-29 00:00:06,086: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8090
 * Running on http://192.168.216.126:8090]
[2025-06-29 00:00:06,089: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-29 00:00:23,133: INFO: _internal: 127.0.0.1 - - [29/Jun/2025 00:00:23] "GET / HTTP/1.1" 200 -]
[2025-06-29 00:00:23,221: INFO: _internal: 127.0.0.1 - - [29/Jun/2025 00:00:23] "[33mGET /static/assets/img/form-v9.jpg HTTP/1.1[0m" 404 -]
[2025-06-29 00:00:23,277: INFO: _internal: 127.0.0.1 - - [29/Jun/2025 00:00:23] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-06-29 00:00:39,114: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-29 00:00:39,119: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-29 00:00:39,123: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-29 00:00:39,127: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-29 00:00:39,128: INFO: common: created directory at: artifacts]
[2025-06-29 00:00:39,129: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-29 00:00:39,130: INFO: data_ingestion: File already exists]
[2025-06-29 00:00:39,142: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-29 00:00:39,142: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-06-29 00:00:39,145: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-29 00:00:39,146: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-29 00:00:39,149: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-29 00:00:39,151: INFO: common: created directory at: artifacts]
[2025-06-29 00:00:39,152: INFO: common: created directory at: artifacts/data_validation]
[2025-06-29 00:00:39,194: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-06-29 00:00:39,194: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-06-29 00:00:39,201: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-29 00:00:39,202: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-29 00:00:39,205: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-29 00:00:39,205: INFO: common: created directory at: artifacts]
[2025-06-29 00:00:39,206: INFO: common: created directory at: artifacts/data_transformation]
[2025-06-29 00:00:39,248: INFO: data_transformation: Splited data into training and test sets]
[2025-06-29 00:00:39,249: INFO: data_transformation: (1199, 12)]
[2025-06-29 00:00:39,250: INFO: data_transformation: (400, 12)]
[2025-06-29 00:00:39,251: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-06-29 00:00:39,251: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-06-29 00:00:39,255: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-29 00:00:39,256: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-29 00:00:39,259: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-29 00:00:39,259: INFO: common: created directory at: artifacts]
[2025-06-29 00:00:39,259: INFO: common: created directory at: artifacts/model_trainer]
[2025-06-29 00:00:39,409: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-06-29 00:00:39,410: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-06-29 00:00:39,414: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-29 00:00:39,415: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-29 00:00:39,418: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-29 00:00:39,419: INFO: common: created directory at: artifacts]
[2025-06-29 00:00:39,420: INFO: common: created directory at: artifacts/model_evaluation]
[2025-06-29 00:00:42,112: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2025-06-29 00:00:46,853: ERROR: main: INTERNAL_ERROR: Response: {'error': 'unsupported endpoint, please contact support@dagshub.com'}]
Traceback (most recent call last):
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\main.py", line 57, in <module>
    data_ingestion.initiate_model_evaluation()
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\src\datascience\pipeline\model_evaluation.py", line 15, in initiate_model_evaluation
    model_evaluation.log_into_mlflow()
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\src\datascience\components\model_evaluation.py", line 66, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model", registered_model_name="ElasticnetModel")
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\sklearn\__init__.py", line 426, in log_model
    return Model.log(
           ^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\models\model.py", line 1161, in log
    model = mlflow.initialize_logged_model(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\tracking\fluent.py", line 2130, in initialize_logged_model
    model = _create_logged_model(
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\tracking\fluent.py", line 2257, in _create_logged_model
    return MlflowClient().create_logged_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\tracking\client.py", line 5371, in create_logged_model
    return self._tracking_client.create_logged_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 824, in create_logged_model
    return self.store.create_logged_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 936, in create_logged_model
    response_proto = self._call_endpoint(CreateLoggedModel, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 135, in _call_endpoint
    return call_endpoint(
           ^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\utils\rest_utils.py", line 590, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Videos\MLOPS\7-dsprojecte2e\dsproject-e2e\data-venv\Lib\site-packages\mlflow\utils\rest_utils.py", line 304, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INTERNAL_ERROR: Response: {'error': 'unsupported endpoint, please contact support@dagshub.com'}
[2025-06-29 00:00:47,396: INFO: _internal: 127.0.0.1 - - [29/Jun/2025 00:00:47] "GET /train HTTP/1.1" 200 -]
[2025-06-29 00:01:03,119: INFO: _internal: 127.0.0.1 - - [29/Jun/2025 00:01:03] "GET /predict HTTP/1.1" 200 -]
[2025-06-29 00:01:03,185: INFO: _internal: 127.0.0.1 - - [29/Jun/2025 00:01:03] "[33mGET /static/assets/img/form-v9.jpg HTTP/1.1[0m" 404 -]
[2025-06-29 00:02:09,204: INFO: _internal: 127.0.0.1 - - [29/Jun/2025 00:02:09] "POST /predict HTTP/1.1" 200 -]
